# -*- coding: utf-8 -*-
"""cli.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UY8T0MiUlBb_tQec6uTzlhf5gxCfgdyq
"""

import click
from pizza import Margherita, Pepperoni, Hawaiian
from typing import Callable
from functools import wraps
import random

Pizza_menu = { "pepperoni": Pepperoni(),
               "margherita": Margherita(),  
               "hawaiian": Hawaiian()}

def log(message: str):    

    def wrapper(func):       

        def inner(*args, **kwargs) -> str:
            
            print(time = random.randint(0, 30))
            res = func(*args, **kwargs)
            return res

        return inner

    return wrapper


@log("👩‍🍳 Приготовим за {} мин")
def bake(pizza):    
    pass


@log("🛵 Доставим пиццу домой через {} мин")
def delivery(pizza):    
    pass

@log("🏡 Можно забрать пиццу домой через {} мин")
def pickup(pizza):    
    pass


@click.group()
def cli():
    pass
 
@cli.command()
@click.option("--delivery", default=False, is_flag=True)
@click.argument("pizza", nargs=1)

def order(pizza, delivery_flag):
    if pizza not in Pizza_menu:
        print(
            "Такой пиццы нет"
        )
        return
    
    if delivery_flag:
        print(bake(pizza), deliver(pizza), sep="\n")
    else:
        print(bake(pizza), pickup(pizza), sep="\n")
    
@cli.command()
def menu():
    for pizza in Pizza_menu.values():
        print(f'- {pizza}: {", ".join(pizza.dict())}')

if __name__ == "__main__":
     Cli()