# -*- coding: utf-8 -*-
"""cli.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UY8T0MiUlBb_tQec6uTzlhf5gxCfgdyq
"""

from unittest.mock import patch
import pytest
import random
from pizza import Margherita, Pepperoni, Hawaiian

def test_dict():
    assert Pepperoni().dict() == {
        "tomato_sauce": 90,
        "mozzarella": 1,
        "tomatoes": 20,
    }
    
def test_different_size_pizza():
    with pytest.raises(ValueError):
        Margherita(size="XS")        
        
def test_pickup():
    with patch.object(random, "randint", return_value=10):
        assert pickup() == "🏡 Можно забрать пиццу домой через 10 мин"
        
def test_delivery():
    with patch.object(random, "randint", return_value=10):
        assert delivery() == "🛵 Доставим пиццу домой через 10 мин"        
        
def test_pizza_size_equal():
    assert Pepperoni(size="L") != Pepperoni(size="XL")
